### ISSUE TITLE
Unable to view the task hubs and durable monitor

### ISSUE THREAD

**Issue by prerna-tesser** [microsoft/azcode#34]
Hi, 
Azure account - prerna@tesserinsights.com
I am unable to view the durable functions monitor on my function app and neither am I able to view the other task hubs under the durable functions section on vs code. I use a Mac device - 11.6. Attaching screenshots of the issue:
<img width="216" alt="Screenshot 2021-12-21 at 11 40 39 AM" src="https://user-images.githubusercontent.com/82448615/146880457-a0c53b32-a9fe-4f87-860c-62b13a43b897.png">
<img width="248" alt="Screenshot 2021-12-21 at 11 40 50 AM" src="https://user-images.githubusercontent.com/82448615/146880463-0b4dd05f-3b4f-467f-a7a7-e4fa624c18f2.png">

**Comment by nturinski** [comment]
Based off of the error that you are receiving, I think whatever extension you are using relies on this extension: https://marketplace.visualstudio.com/items?itemName=DurableFunctionsMonitor.durablefunctionsmonitor

I'm pretty sure that this is not coming from one of our extensions though.  Do you know which extension is contributing that view?

**Comment by prerna-tesser** [comment]
It is the extension of the durable functions monitor itself. However, the extension is not allowing me to see the subscription account under the Durable Functions section
<img width="214" alt="Screenshot 2021-12-22 at 8 39 13 AM" src="https://user-images.githubusercontent.com/82448615/147028961-fee9dd09-b381-49b2-afa9-02286dd399d5.png">
.

**Comment by wwlorey** [comment]
Unfortunately this team can't help with problems related to the Durable Functions Monitor Extension. Please log your issue here: https://github.com/microsoft/DurableFunctionsMonitor.
