### ISSUE TITLE
Error with Logic Apps (Standard) Extension for vscode

### ISSUE THREAD

**Issue by jcetina** [microsoft/azcode#36]
I'm using VSCode on Mac OS Big Sur.

Whenever I try to create a logic app project using the aforementioned extension, I get the following error:

`You must have the .NET Core SDK installed to perform this operation. See here for supported versions.`

I've tried using both .NET Core 5 and 6 (uninstalling the other version each time), and it's always the same error. The error comes when I select the type of workflow (Stateful or Stateless) in the `Create New Project` dialogs.

**Comment by wwlorey** [comment]
Hi @jcetina, thanks for filing. Unfortunately this team doesn't work on the Logic Apps extension. Please re-file your issue on that repo [here](https://github.com/microsoft/vscode-azurelogicapps/issues/new).
