### ISSUE TITLE
Unable to see Azure Cache for Redis servers in Azure US Government

### ISSUE THREAD

**Issue by felpel** [microsoft/azcode#38]
After I log into my **Azure US Government** account, I'm able to see the following resource types without any issue:
- Azure Functions.
- Azure Resource Groups (and inner resources).

For Azure Cache for Redis, under all the subscriptions I have access to, I see the following message:
> Error: Entry not found in cache.

**Comment by felpel** [comment]
Hi @nturinski, I tried to reload the window and it didn't solve this issue.

Here is a preview of what I see:

![image](https://user-images.githubusercontent.com/5000004/159982607-6ff36817-c9b4-450b-8f80-415ccc1384c8.png)

**Comment by felpel** [comment]
I forgot to mention it in the initial message, but I did do the whole sign out/sign in approach without any success.

**Comment by nturinski** [comment]
Okay, thanks for troubleshooting with us.  We'll have to investigate exactly what's going on here.  

Last thing, did this subscription ever work or is this a new issue?

**Comment by felpel** [comment]
It never worked for Redis resources, but I'm able to see other resource types for the same subscriptions. I have access to roughly 4 different Azure subscriptions in that cloud as well with an identical buggy behavior.

**Comment by nturinski** [comment]
Actually, I just noticed that your view pane says "Caches" on it. This extension is managed on this repo https://github.com/microsoft/vscode-azurecache.  

Could you file the issue there?  Though unfortunately, it doesn't seem like it's very active 😞

**Comment by wwlorey** [comment]
Closing as external bug.
