### ISSUE TITLE
recover deleted apim apis

### ISSUE THREAD

**Issue by Kelele-m3** [microsoft/azcode#53]
i need urgent help regrading azure apim. Here is my question;

I was working on implmenting git version controlling for apim policies that i was workng in the azure portal tools. I have installed Azure API Management extension for VS Code, & i was able to sync it with azure portal policies, but i accidentaly deleted the apis from the VS Code but all apis in azure portal got automatically deleted, is it possible to recover those apis in the azure portal.

I am beginner, I did nothing, confused & shocked.

**Comment by nturinski** [comment]
Sorry for the very late response.  We actually aren't the team responsible for the API Management Extension. I hope you were able to figure this out, but if you still need help, please reach out to this repository: https://github.com/Microsoft/vscode-apimanagement.
